name: 'tpch_dimensional'
version: '1.0.0'
profile: 'tpch_dimensional'
config-version: 2

on-run-start:
  - "{{ insert_audits('run_start') }}"

on-run-end:
  - "{{ insert_audits('run_end') }}"

models:
  tpch_dimensional:
    +pre-hook: "{{ insert_audits('model_start') }}"
    +post-hook: "{{ insert_audits('model_end') }}"
    staging:
      +materialized: table
      +schema: staging
      +tags: ['staging']
    transformation:
      +materialized: view
      +schema: transformation
      +tags: ['transformation']
      +grants:
        select: "{{ [env_var('DBT_CONSUMER_ROLE', 'REPORTER')] if target.name == 'prod' else [] }}"

    business:
      +materialized: table
      +schema: business
      +tags: ['business']
      +grants:
        select: "{{ [env_var('DBT_CONSUMER_ROLE', 'REPORTER')] if target.name == 'prod' else [] }}"

