name: 'tpch_dimensional'
version: '1.0.0'
profile: 'tpch_dimensional'
config-version: 2

on-run-start:
  - "INSERT INTO TPCH_DWH.PUBLIC.DBT_AUDITS (audit_type, created_at) VALUES
   ('run_start', CONVERT_TIMEZONE('Europe/Madrid', 
   CURRENT_TIMESTAMP())); COMMIT;"

on-run-end:
  - "INSERT INTO TPCH_DWH.PUBLIC.DBT_AUDITS (audit_type, created_at) VALUES 
    ('run_end', CONVERT_TIMEZONE('Europe/Madrid', CURRENT_TIMESTAMP())); COMMIT;"


models:
  tpch_dimensional:
    staging:
      +materialized: table
      +schema: staging
    transformation:
      +materialized: view
      +schema: transformation
    business:
      +materialized: table
      +schema: business
